apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: credit-scoring-fe-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/your-group/credit-scoring-new.git
    targetRevision: main
    path: deploy/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: credit-scoring-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
