apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: credit-scoring-prod
resources:
  - ../../base
  - externalsecret.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
images:
  - name: registry.example.com/credit-scoring/fe
    newTag: prod-latest
