apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: credit-scoring-fe-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: credit-scoring-fe-secrets
    creationPolicy: Owner
  data:
    - secretKey: BACKEND_API_URL
      remoteRef:
        key: credit-scoring-fe-dev-backend-api-url
